name:                poly-sessions
version:             0.1.0
github:              dcastrop/poly-sessions
license:             BSD3
author:              David Castro-Perez
maintainer:          d.castro-perez@imperial.ac.uk
copyright:           2017 David Castro-Perez

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dcastrop/poly-sessions#readme>

dependencies:
- base >= 4.9 && < 5
- containers >= 0.5 && < 0.6
- quoted-prettyprinter >= 0.1 && < 0.2
- constrained-control >= 0.1 && < 0.2
- ivector >= 0.1 && < 0.2
- deep-sessions >= 0.1 && < 0.2
- poly-lang >= 0.2 && < 0.3
- mtl >= 2.2 && < 2.3
- prettyprinter >= 1.2 && < 1.3
- singletons >= 2.4 && < 2.5
- constraints >= 0.10 && < 0.11
- extra >= 1.6 && < 1.7
- ghc-typelits-natnormalise >= 0.6 && < 0.7
- ghc-typelits-knownnat >= 0.5 && < 0.6
# - monadplus >= 1.4 && < 1.5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  exposed-modules:
  - Language.SessionTypes.RwSession

executables:
  poly-session:
    main:                PolySession.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - poly-sessions

tests:
  poly-sessions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - poly-sessions
