resolver: lts-9.14
packages:
- .

extra-deps:
# - https://github.com/dcastrop/poly-lang/archive/v0.2.0.zip
# - https://github.com/dcastrop/quoted-prettyprinter/archive/v0.1.1.tar.gz
# - https://github.com/dcastrop/deep-sessions/archive/v0.1.0.zip
- ../../poly-lang/code
- ../../deep-sessions/code
- ../../quoted-prettyprinter/code
- ../../tcontrol/code
- type-natural-0.8.1.0
- equational-reasoning-0.5.1.0
- ghc-typelits-presburger-0.2.0.0


flags: {}
extra-package-dbs: []
