resolver: nightly-2018-06-11

packages:
- .

extra-deps:
# - https://github.com/dcastrop/poly-lang/archive/v0.2.0.zip
# - https://github.com/dcastrop/quoted-prettyprinter/archive/v0.1.1.tar.gz
# - https://github.com/dcastrop/deep-sessions/archive/v0.1.0.zip
- git: https://github.com/dcastrop/quoted-prettyprinter
  commit: HEAD
- git: https://github.com/dcastrop/constrained-control
  commit: HEAD
- git: https://github.com/dcastrop/IVector
  commit: HEAD
- git: https://github.com/dcastrop/poly-lang
  commit: HEAD
- git: https://github.com/dcastrop/deep-sessions
  commit: HEAD

flags: {}
extra-package-dbs: []
