resolver: lts-9.14
packages:
- .

extra-deps:
# - https://github.com/dcastrop/poly-lang/archive/v0.2.0.zip
# - https://github.com/dcastrop/quoted-prettyprinter/archive/v0.1.1.tar.gz
# - https://github.com/dcastrop/deep-sessions/archive/v0.1.0.zip
- ../../poly-lang/code
- ../../deep-sessions
- ../../quoted-prettyprinter/code

flags: {}
extra-package-dbs: []
